package com.reynaldiwijaya.smartrt.Helper;

public class Constant {
    public static final String BASE_URL = "https://lombadinacom.000webhostapp.com/Dinacom/";
    public static final String IMAGE_INFORMASI_URL = "https://lombadinacom.000webhostapp.com/Dinacom/upload_informasi/";
    public static final String UPLOAD_URL = "https://lombadinacom.000webhostapp.com/Dinacom/insertnews.php";
    public static final String UPLOAD_URL_STORE = "https://lombadinacom.000webhostapp.com/Dinacom/insertstore.php";
    public static final String UPLOAD_REGISTER_URL = "https://lombadinacom.000webhostapp.com/Dinacom/register.php";
    public static final String IMAGE_USER_URL = "https://lombadinacom.000webhostapp.com/Dinacom/upload/";
    public static final String IMAGE_STORE_URL = "https://lombadinacom.000webhostapp.com/Dinacom/storeupload/";
    public static final String INDONESIA_NEWS = "https://newsapi.org/";
    public static final String API_INDONESIA_NEWS = "72b0da4102224254a299c4d63080c4e6";
    public static final int REQ_CHOOSE_FILE_REGISTER = 100;
    public static final int REQ_CHOOSE_FILE_NEWS = 101;
    public static final int STORAGE_REQUEST_PERMISSION = 200;
    public static final String ID_USER = "id";
    public static final String NAMA = "nama";
    public static final String NO_KTP = "no";
    public static final String ALAMAT = "alamat";
    public static final String STATUS = "status";
    public static final String DATE = "date";
    public static final String JENKEL = "jenkel";
    public static final String PROFESI = "profesi";
    public static final String NO_TLP = "no_tlp";
    public static final String EMAIL = "email";
    public static final String FOTO = "foto";
    public static final String LEVEL = "level";
    public static final String KEY_ID = "key_id";
    public static final String JUDUL = "judul";
    public static final String CONTENT = "content";
    public static final String TEMPAT = "tempat";
    public static final String TANGGAL = "tanggal";
    public static final String DESKRIPSI = "deskripsi";
    public static final String NO_TLP_STORE = "no_tlp_store";
    public static final String NAMA_TOKO = "nama_toko";
    public static final String FOTO_INFORMASI = "foto_informasi";
    public static final String FOTO_STORE = "foto_toko";
    public static final String REPLY = "reply";
    public static final String OBJ = "obj";
}
